export default {
  '手机验证码登录/注册': 'Phone Verification Code Login/Registration',
  手机号: 'Phone Number',
  验证码: 'Verification Code',
  输入验证码: 'Enter Verification Code',
  输入您的手机号: 'Enter Your Phone Number',
  获取验证码: 'Get Verification Code',
  秒后重新获取: 'Seconds to Retry',
  切换为密码登陆: 'Switch to Password Login',
  '登陆/注册': 'Login/Register',
  '未注册手机验证后自动登录，注册即代表同意':
    'Unregistered phones will automatically log in after verification. Registration means agreeing to this.',
  和: 'and',
  密码登录: 'Password Login',
  输入您的用户名或手机号: 'Enter Your Username or Phone Number',
  用户名或手机号: 'Username or Phone Number',
  用户名: 'Username',
  密码: 'Password',
  输入密码: 'Enter Password',
  切换为验证码登陆: 'Switch to Phone Verification Code Login',
  '忘记密码？': 'Forgot Password?',
  登录: 'Login',
  '还没有账号？': "Don't have an account?",
  鹦鹉智学协议: 'ParrotBot AI Learning Agreement',
  隐私协议: 'Privacy Agreement',
  马上注册: 'Register Now',
  '请输入你的手机号！': 'Please Enter Your Phone Number!',
  '请输入正确的手机号！': 'Please Enter a Valid Phone Number!',
  '请输入验证码！': 'Please Enter the Verification Code!',
  NEXT: 'Next',
  BACK: 'Back',
  阅读题库: 'Reading Question Bank',
  听力题库: 'Listening Question Bank',
  口语题库: 'Speaking Question Bank',
  写作题库: 'Writing Question Bank',
  下午好: 'Good Afternoon',
  上午好: 'Good Morning',
  目前预测分数: 'Current Predicted Score',
  已经学习天数: 'Days Studied',
  距离考试天数: 'Days Until Exam',
  今日任务: "Today's Tasks",
  明日任务: "Tomorrow's Tasks",
  专项训练: 'Specialized Training',
  长难句学习: 'Complex Sentence Learning',
  通过AI辅助学习轻松掌握长难句的语法和翻译技巧:
    'Easily master the grammar and translation of complex sentences with AI-assisted learning',
  题型学习: 'Question Type Study',
  文章逻辑: 'Passage Logic',
  训练与模考: 'Training and Mock Exams',
  错题精选: 'Selected Wrong Questions',
  模拟考试: 'Mock Exam',
  去完成: 'Complete',
  '暂无当日任务，请先完成模拟考试获取定制任务':
    'There are no tasks left for today, please complete the mock exam to get customized tasks.',
  '开始模考 ': 'Start Mock Exam',
  模考: 'Mock Exam',
  练习: 'Practice',
  请选择此次模考文章: 'Please Select a Mock Exam Passage',
  请选择此次练习文章: 'Please Select a Practice Passage',
  取消: 'Cancel',
  确定: 'Confirm',
  未完成: 'Incomplete',
  继续考试: 'Continue Exam',
  进度: 'Progress',
  帮助: 'Help',
  上一步: 'Previous',
  下一步: 'Next',
  提交: 'Submit',
  模考得分: 'Mock Exam Score',
  模考小结: 'Mock Exam Summary',
  回顾答案: 'Review Answers',
  'TPO1-阅读': 'TPO1-Reading',
  'TPO1-听力': 'TPO1-Listening',
  'TPO1-口语': 'TPO1-Speaking',
  'TPO1-写作': 'TPO1-Writing',
  学习记录: 'Study Records',
  未测试: 'Not Tested',
  当前词汇量: 'Current Vocabulary Size',
  今日学习: "Today's Study",
  今日复习: "Today's Review",
  总计学习: 'Total Study',
  总计复习: 'Total Review',
  单词学习曲线: 'Vocabulary Learning Curve',
  单词学习进度: 'Vocabulary Learning Progress',
  '4/6级单词': 'College English Test 4/6 Vocabulary',
  重选: 'Reselect',
  托福核心词: 'TOEFL Core Vocabulary',
  托福高频词: 'TOEFL High-Frequency Vocabulary',
  跳过: 'Skip',
  托福真题词: 'TOEFL Real Test Vocabulary',
  选择: 'Select',
  托福学科词: 'TOEFL Subject Vocabulary',
  学习新单词: 'Learn New Vocabulary',
  复习旧单词: 'Review Old Vocabulary',
  重新测量词汇量: 'Retest Vocabulary Size',
  总计: 'Total',
  个: 'Items',
  鹦鹉AI助教: 'ParrotBot AI Teaching Assistant',
  小啾预测题是AI自动生成的写作题目: 'Xiaoqius predicted questions are AI-generated writing topics',
  帮您更好地迎战新的写作考核模式: 'Helping you better prepare for the new writing assessment model',
  小啾预测题: 'Xiaoqius Predicted Questions',
  继续完成: 'Continue Completing',
  未开始: 'Not Started',
  进行中: 'In Progress',
  已完成: 'Completed',
  '此功能为会员功能，如需使用请在“价格”页购买会员':
    'This function is for members only, please purchase membership on the "Pricing" page if needed',
  'Your browser does not support the audio element':
    'Your browser does not support the audio element',
  暂无数据: 'No Data',
  查看原题: 'View Original Question',
  查看报告: 'View Report',
  评分: 'Score',
  原版录音与文字转换: 'Original Recording-To-Text Conversion',
  原版: 'Original',
  '🔒您的今日免费批改次数已用尽': '🔒Your free correction quota for today has been exhasuted.',
  '如需批改，请购买会员': 'Please purchase membership if you need correction',
  购买会员: 'Purchase Membership',
  问题标注: 'Question Annotation',
  返回: 'Return',
  错题: 'Wrong Questions',
  '正在打分中...': 'Scoring...',
  播放听力材料: 'Play Listening Material',
  快速导航: 'Quick Navigation',
  上一题: 'Previous Question',
  下一题: 'Next Question',
  查看批注: 'View Annotations',
  口语阅读原文: 'Reading/Speaking Original Text',
  返回主页: 'Return to Homepage',
  编辑头像: 'Edit Profile Picture',
  删除: 'Delete',
  账户信息: 'Account Information',
  修改密码: 'Change Password',
  修改手机号: 'Change Phone Number',
  通知提醒管理: 'Notification Management',
  隐私条款: 'Privacy Policy',
  查看: 'View',
  反馈意见: 'Give Your Feedback',
  添加企业微信: 'Add WeChat for Business',
  客服邮箱: 'Customer Service Email',
  'frank_fan@parrotbot.cn': 'frank_fan@parrotbot.cn',
  确认: 'Confirm',
  原手机号: 'Original Phone Number',
  设置新手机号: 'Set New Phone Number',
  目标管理: 'Goal Management',
  周报总结: 'Weekly Summary',
  开始你的学习第一步: 'Start Your First Step of Learning',
  '在开始之前，我们希望通过几个问题来了解您的学习目标和期望，来为您制定最适合的学习方案。':
    'Before we start, we would like to understand your learning goals and expectations with a few questions to tailor the best learning plan for you.',
  跳到: 'Skip to',
  这座小山已经容不下你了: 'This small hill can no longer accommodate you',
  '您的正确率过高，推荐您跳级下一个词库':
    'Your accuracy is too high, we recommend skipping to the next word bank',
  '自行跳过词库可能让您词汇掌握不扎实，且不能跳回原来的等级。为保证快速提升成绩，我们会从最基础的词库开始查漏补缺。当我们发现您已经掌握这个词库时，会主动提醒您更新到更高级的词汇库。':
    'Skipping word banks on your own may result in an unstable grasp of vocabulary, and you cannot return to the previous level. To ensure rapid improvement, we will start with the most basic word bank to identify and fill gaps. When we find that you have mastered this word bank, we will notify you to move up to a more advanced word bank.',
  鹦鹉智学AI单词背诵: 'ParrotBot AI Vocabulary Recitation',
  '鹦鹉智学AI单词背诵会使用生词用AI生成文章来辅助背诵。这种背诵方式功能会让你的背诵记忆更加牢固、快速，也更加适应托福考试的要求。在我们过去做的实验中，100%的学生认为背诵效果提升，100%的学生认为这让单词背诵变得有趣。':
    'ParrotBot AI vocabulary recitation uses AI-generated passages with unfamiliar vocabulary to aid memorization. This method makes your memorization more solid and better adapted to TOEFL requirements. In our past experiments, 100% of students found that this method improved their memorization and made word recitation more enjoyable.',
  '鹦鹉智学 4步AI背诵法': 'ParrotBot AI 4-Step AI Recitation Method',
  AI筛选生词: 'AI-Filtered Vocabulary',
  AI生词生成文章: 'AI-Generated Passage with New Vocabulary',
  语境单词背诵: 'Contextual Vocabulary Recitation',
  AI模考复习: 'AI Mock Exam Review',
  已学习单词: 'Vocabulary Learned',
  发现生词: 'Discover New Vocabulary',
  直接进入背诵: 'Directly Enter Recitation',
  '的意思是？': 'means?',
  不认识该词: "Don't Recognize This Vocabulary",
  恭喜你完成了今天的任务: "Congratulations on Completing Today's Task",
  返回单词首页: 'Return to Vocabulary Homepage',

  学习目标: 'Learning Goals',
  问题1: 'Question 1',
  '您目前的学习阶段是？': 'What is Your Current Learning Stage?',
  问题2: 'Question 2',
  '您的学习目的是？': 'What is Your Learning Purpose?',
  问题3: 'Question 3',
  '您是否正在机构补习托福？': 'Are You Currently Taking TOEFL Tutoring at an Institution?',
  问题: 'Question',
  每日打卡: 'Daily Check-In',
  每日学习30分钟以上即完成当日: 'Studying for More Than 30 Minutes a Day Completes the Daily Task',
  '打卡任务！加油哦！': 'Check-in Task! Keep Going!',
  '暂无学习诊断，快去学习吧～': 'No Study Diagnosis Yet, Go Study~',
  近7日平均分: 'Average Score of the Last 7 Days',
  错误率最高的题型: 'Question Type with the Highest Error Rate',
  您的当前词汇量为: 'Your Current Vocabulary Size Is',
  近七日访问次数: 'Number of Visits in the Last Seven Days',
  选择你的托福考试时间: 'Choose Your TOEFL Exam Time',
  年: 'Year',
  月: 'Month',
  忘记密码: 'Forgot Password',
  综合模考: 'Comprehensive Mock Exam',
  '做任务免费领取会员!': 'Complete Tasks to Get Free Membership!',
  查看详情: 'View Details',
  '无限接近真实考试题，有几率在真实考试中复现。':
    'Almost identical to the real exam questions, with a chance to appear in the actual exam.',
  免费版: 'Free Version',
  '0元/月': '0 Yuan/Month',
  '免费使用我们所有模考，练习系统以及预测题，并获得个人问题诊断。':
    'Free use of all our mock exams, practice systems, and prediction questions, and receive personal issue diagnosis.',
  '免费提供每日一次口语写作批改功能辅助您的学习。':
    'Free daily correction function for speaking and writing to assist your study.',
  '5月前注册赠送1年留学顾问。扫描企业微信领取':
    'Register before May to get a one-year study abroad consultant. Scan WeChat for Business to receive.',
  最受欢迎: 'Most Popular',
  练习版会员: 'Practice Version Membership',
  '49元/月': '49 Yuan/Month',
  '您可使用我们软件的全部功能：包括每日30题批改，实时答疑，单词无痛背诵，全能版心理支持等功能。':
    'You can use all the functions of our software: including daily correction of 30 questions, real-time Q&A, painless vocabulary memorization, comprehensive psychological support, and more.',
  '赠送：三年留学顾问': 'Bonus: Three-Year Study Abroad Consultant',
  自适应学习版: 'Adaptive Learning Version',
  即将推出: 'Coming Soon',
  '在练习版会员的基础上，您将获得网课及每日智能任务功能。':
    'In addition to the practice version membership, you will get online courses and daily intelligent task functions.',
  '我们将附赠您12个月会员及终身留学顾问。':
    'We will give you 12 months of membership and a lifetime study abroad consultant.',
  扫码联系客服: 'Scan to Contact Customer Service',
  领取礼包: 'Get Gift Package',
  汉语: 'Chinese',
  英语: 'English',
  匈牙利语: 'Hungarian',
  请选择语言模式: 'Please select a language mode',
  打开网站提醒: 'Open Website Alerts',
  打开短信提醒: 'Turn on SMS alerts',
  个人账号: 'Personal account',
  关于鹦鹉智学: 'About ParrotBot',
  成绩计算中: 'Score calculation',
  题库加载中: 'Question bank loading',
  价格: 'Price',
  设置: 'Setting',
  看板: 'Dashboard',
  阅读: 'Read',
  听力: 'Listen',
  口语: 'Speak',
  写作: 'Write',
  单词背诵: 'Vocabulary Recitation',
  我的任务: 'MyTask',
  个人学习诊断: 'PersonalLearningDiagnosis',
  试题加载中: 'Question loading',
  单词练习: 'Vocabulary Practice',
  输入你想问的问题: 'Enter your question',
  输入消息: 'Enter Message',
  'nice to meet you':
    'Hi\n there! \nNice \nto \nmeet \nyou! If \nyou \nhave \nany \nquestions \nabout \nTOEFL \nlearning, \nfeel \nfree \nto \nask \nme!'
}
