export default {
  'NEXT': "NEXT",
  'BACK': "BACK",
  '验证码登录/注册': 'Verification code login/registration',
  '阅读题库': "Reading question bank",
  '输入您的手机号': "Enter your number",
  '手机号': "Number",
  '验证码': "Verification code",
  '输入验证码': "Enter verification code",
  '获取验证码': "Get Code",
  '秒后重新获取': "Get it again in seconds",
  '切换为密码登陆': "Switch to password login",
  '登陆/注册': "Login/Registration",
  '未注册的手机号验证通过后将直接注册': "The unregistered number will be registered directly after verification",
  '密码登录': "Password login",
  '输入您的用户名或手机号': "Enter your username or number",
  '用户名或手机号': 'User name or number',
  '密码': "Password",
  '输入密码': "Enter password",
  '切换为验证码登陆': "Switch to verification code login",
  '忘记密码？': "Forget password?",
  '登录': "Log in",
  '还没有账号？': "No account?",
  '马上注册': "Register",
  '目前预测分数': "Current forecast score",
  '已经学习天数': "Number of days studied", 
  '距离考试天数': "Days until test",
  '专项训练': "Special training",
  '长难句学习': "Long difficult sentence learning",
  '通过AI辅助学习轻松掌握长难句的语法和翻译技巧': "",
  '题型学习': "",
  '文章逻辑': "",
  '训练与模考': "",
  '错题精选': "",
  '模拟考试': "",
  '去完成':""
}