export default {
  'NEXT': "NEXT",
  'BACK': "BACK",
  '验证码登录/注册': 'Phone Verification/Login',
  '阅读题库': "Reading Question Bank",
  '听力题库': "Listening Question Bank",
  '口语题库': "Speaking Question Bank",
  '写作题库': "Writing Question Bank",
  '输入您的手机号': "Enter Your Phone Number",
  '手机号': "Phone Number",
  '验证码': "Verification Code",
  '输入验证码': "Enter Verification Code",
  '获取验证码': "Get Verification Code",
  '秒后重新获取': "Seconds to Retry",
  '切换为密码登陆': "Switch to Password Login",
  '登陆/注册': "Login/Register",
  '未注册的手机号验证通过后将直接注册': "Unregistered phone numbers will be registered directly after verification.",
  '密码登录': "Password Login",
  '输入您的用户名或手机号': "Enter Your Username or Phone Number",
  '用户名或手机号': 'Username or Phone Number',
  '密码': "Password",
  '输入密码': "Enter Password",
  '切换为验证码登陆': "Switch to Verification Code Login",
  '忘记密码？': "Forget Password?",
  '登录': "Log in",
  '还没有账号？': "Don't have an account yet?",
  '马上注册': "Register Now",
  '下午好': "Good afternoon",
  '上午好': "Good morning",
  '目前预测分数': "Current Predicted Score",
  '已经学习天数': "Days Studied",
  '距离考试天数': "Days Until Exam",
  '今日任务': "Today's Tasks",
  '明日任务': "Tomorrow's Tasks",
  '专项训练': "Specialized Training",
  '长难句学习': "Advanced Sentence Learning",
  '通过AI辅助学习轻松掌握长难句的语法和翻译技巧': "Easily master the grammar and translation skills of complex sentences with AI assistance.",
  '题型学习': "Question Type Learning",
  '文章逻辑': "Article Logic",
  '训练与模考': "Training and Simulated Exams",
  '错题精选': "Selected Incorrect Answers",
  '模拟考试': "Mock Exam",
  '去完成': "Go to Complete",
  '暂无当日任务，请先完成模拟考试获取定制任务': "No tasks for today. Please complete a mock exam to get customized tasks.",
  '开始模考 ': "Start Mock Exam",
  '模考': "Mock",
  '练习': "Practice",
  '请选择此次模考文章': "Select the article for this mock exam",
  '请选择此次练习文章': "Select the article for this practice",
  '取消': "Cancel",
  '确定': "Confirm",
  '未完成': "Unfinished",
  '继续考试': "Continue Exam",
  '进度': "Progress",
  '帮助': "Help",
  '上一步': "Previous Step",
  '下一步': "Next Step",
  '提交': "Submit",
  '模考得分': "Mock Exam Score",
  '模考小结': "Mock Exam Summary",
  '回顾答案': "Review Answers",
  'TPO1-阅读': "TPO1-Reading",
  'TPO1-听力': "TPO1-Listening",
  'TPO1-口语': "TPO1-Speaking",
  'TPO1-写作': "TPO1-Writing",
  '学习记录': "Learning Records",
  '未测试': "Not Tested",
  '当前词汇量': "Current Vocabulary",
  '今日学习': "Today's Learning",
  '今日复习': "Today's Review",
  '总计学习': "Total Learning",
  '总计复习': "Total Review",
  '单词学习曲线': "Word Learning Curve",
  '单词学习进度': "Word Learning Progress",
  '4/6级单词': "CET-4/CET-6 Vocabulary",
  '重选': "Reselect",
  '托福核心词': "TOEFL Core Words",
  '托福高频词': "TOEFL High-Frequency Words",
  '跳过': "Skip",
  '托福真题词': "TOEFL Real Exam Words",
  '选择': "Select",
  '托福学科词': "TOEFL Subject Words",
  '学习新单词': "Learn New Words",
  '复习旧单词': "Review Old Words",
  '重新测量词汇量': "Remeasure Vocabulary",
  '总计': "Total",
  '个': "",
  '鹦鹉AI助教': "Parrot AI Assistant",
};
