export default {
  '手机验证码登录/注册': 'Mobil hitelesítési kóddal bejelentkezés/regisztráció',
  手机号: 'Telefonszám',
  验证码: 'Hitelesítési kód',
  输入验证码: 'Adja meg a hitelesítési kódot',
  输入您的手机号: 'Adja meg a telefonszámát',
  获取验证码: 'Hitelesítési kód kérése',
  秒后重新获取: 'Újra kérhető másodperc múlva',
  切换为密码登陆: 'Váltás jelszavas bejelentkezésre',
  '登陆/注册': 'Bejelentkezés/Regisztráció',
  '未注册手机验证后自动登录，注册即代表同意': 'Nem regisztrált telefonok automatikusan bejelentkeznek hitelesítés után, a regisztráció egyben elfogadja a',
  和: 'és',
  密码登录: 'Jelszavas bejelentkezés',
  输入您的用户名或手机号: 'Adja meg a felhasználónevet vagy telefonszámot',
  用户名或手机号: 'Felhasználónév vagy telefonszám',
  密码: 'Jelszó',
  输入密码: 'Adja meg a jelszót',
  切换为验证码登陆: 'Váltás hitelesítési kóddal történő bejelentkezésre',
  '忘记密码？': 'Elfelejtette a jelszavát?',
  登录: 'Bejelentkezés',
  '还没有账号？': 'Még nincs fiókja?',
  鹦鹉智学协议: 'Papagáj Okos Tanulási Megállapodás',
  隐私协议: 'Adatvédelmi Megállapodás',
  马上注册: 'Regisztráljon most',
  '请输入你的手机号！': 'Adja meg a telefonszámát!',
  '请输入正确的手机号！': 'Adja meg a helyes telefonszámot!',
  '请输入验证码！': 'Adja meg a hitelesítési kódot!',
  NEXT: 'Következő',
  BACK: 'Vissza',
  阅读题库: 'Olvasási Kérdésbank',
  听力题库: 'Hallgatási Kérdésbank',
  口语题库: 'Beszéd Kérdésbank',
  写作题库: 'Írásbeli Kérdésbank',
  下午好: 'Jó délutánt',
  上午好: 'Jó reggelt',
  目前预测分数: 'Jelenlegi előrejelzett pontszám',
  已经学习天数: 'Tanulási napok száma',
  距离考试天数: 'Vizsgáig hátralévő napok száma',
  今日任务: 'Mai feladatok',
  明日任务: 'Holnapi feladatok',
  专项训练: 'Speciális képzés',
  长难句学习: 'Hosszú és nehéz mondatok tanulása',
  通过AI辅助学习轻松掌握长难句的语法和翻译技巧: 'Könnyen elsajátíthatja a hosszú és nehéz mondatok nyelvtani és fordítási készségeit AI támogatással',
  题型学习: 'Feladattípus tanulás',
  文章逻辑: 'Cikk logika',
  训练与模考: 'Képzés és próbavizsga',
  错题精选: 'Kiválasztott hibás kérdések',
  模拟考试: 'Próbavizsga',
  去完成: 'Menjen teljesíteni',
  '暂无当日任务，请先完成模拟考试获取定制任务': 'Nincsenek mai feladatok, kérjük, először teljesítse a próbavizsgát, hogy egyedi feladatokat kapjon',
  '开始模考 ': 'Próbavizsga indítása',
  模考: 'Próbavizsga',
  练习: 'Gyakorlás',
  请选择此次模考文章: 'Válassza ki ezt a próbavizsga cikket',
  请选择此次练习文章: 'Válassza ki ezt a gyakorló cikket',
  取消: 'Mégse',
  确定: 'Megerősítés',
  未完成: 'Befejezetlen',
  继续考试: 'Vizsga folytatása',
  进度: 'Haladás',
  帮助: 'Segítség',
  上一步: 'Előző',
  下一步: 'Következő',
  提交: 'Beküldés',
  模考得分: 'Próbavizsga pontszám',
  模考小结: 'Próbavizsga összefoglaló',
  回顾答案: 'Válaszok áttekintése',
  'TPO1-阅读': 'TPO1-Olvasás',
  'TPO1-听力': 'TPO1-Hallgatás',
  'TPO1-口语': 'TPO1-Beszéd',
  'TPO1-写作': 'TPO1-Írás',
  学习记录: 'Tanulási napló',
  未测试: 'Nem tesztelt',
  当前词汇量: 'Jelenlegi szókincs',
  今日学习: 'Mai tanulás',
  今日复习: 'Mai ismétlés',
  总计学习: 'Összes tanulás',
  总计复习: 'Összes ismétlés',
  单词学习曲线: 'Szókincs tanulási görbe',
  单词学习进度: 'Szókincs tanulási előrehaladás',
  '4/6级单词': '4/6 szintű szavak',
  重选: 'Újraválasztás',
  托福核心词: 'TOEFL alapvető szavak',
  托福高频词: 'TOEFL gyakori szavak',
  跳过: 'Átugrás',
  托福真题词: 'TOEFL valós teszt szavak',
  选择: 'Kiválasztás',
  托福学科词: 'TOEFL tantárgyi szavak',
  学习新单词: 'Új szavak tanulása',
  复习旧单词: 'Régi szavak ismétlése',
  重新测量词汇量: 'Szókincs újramérése',
  总计: 'Összesen',
  个: 'Elemek',
  鹦鹉AI助教: 'Papagáj AI oktatási asszisztens',
  小啾预测题是AI自动生成的写作题目: 'Xiaojiu előrejelzett kérdései AI által generált írásbeli témák',
  帮您更好地迎战新的写作考核模式: 'Segít jobban felkészülni az új írásbeli értékelési módra',
  小啾预测题: 'Xiaojiu előrejelzett kérdései',
  继续完成: 'Folytassa a befejezést',
  未开始: 'Nem kezdett',
  进行中: 'Folyamatban',
  已完成: 'Befejezett',
  '此功能为会员功能，如需使用请在“价格”页购买会员':
    'Ez a funkció csak tagok számára elérhető, kérjük, vásároljon tagságot az "Árak" oldalon, ha szükséges',
  'Your browser does not support the audio element':
    'A böngészője nem támogatja az audio elemet',
  暂无数据: 'Nincs adat',
  查看原题: 'Eredeti kérdés megtekintése',
  查看报告: 'Jelentés megtekintése',
  评分: 'Értékelés',
  原版录音与文字转换: 'Eredeti felvétel és szöveg átalakítás',
  原版: 'Eredeti',
  '🔒您的今日免费批改次数已用尽': '🔒A mai ingyenes javítási lehetőségei elfogytak',
  '如需批改，请购买会员': 'Ha javításra van szüksége, kérjük, vásároljon tagságot',
  购买会员: 'Tagság vásárlása',
  问题标注: 'Kérdés megjegyzés',
  返回: 'Vissza',
  错题: 'Hibás kérdések',
  '正在打分中...': 'Értékelés folyamatban...',
  播放听力材料: 'Hallgatási anyag lejátszása',
  快速导航: 'Gyors navigáció',
  上一题: 'Előző kérdés',
  下一题: 'Következő kérdés',
  查看批注: 'Megjegyzések megtekintése',
  口语阅读原文: 'Olvasás/Beszéd eredeti szöveg',
  返回主页: 'Vissza a főoldalra',
  编辑头像: 'Profilkép szerkesztése',
  删除: 'Törlés',
  账户信息: 'Fiók információk',
  修改密码: 'Jelszó megváltoztatása',
  修改手机号: 'Telefonszám megváltoztatása',
  通知提醒管理: 'Értesítési beállítások kezelése',
  隐私条款: 'Adatvédelmi irányelvek',
  查看: 'Megtekintés',
  反馈意见: 'Visszajelzés küldése',
  添加企业微信: 'Vállalati WeChat hozzáadása',
  客服邮箱: 'Ügyfélszolgálat e-mail',
  'frank_fan@parrotbot.cn': 'frank_fan@parrotbot.cn',
  确认: 'Megerősítés',
  原手机号: 'Eredeti telefonszám',
  设置新手机号: 'Új telefonszám beállítása',
  目标管理: 'Célkezelés',
  周报总结: 'Heti összefoglaló',
  开始你的学习第一步: 'Kezdje az első lépést a tanulásban',
  '在开始之前，我们希望通过几个问题来了解您的学习目标和期望，来为您制定最适合的学习方案。':
    'Mielőtt elkezdjük, szeretnénk néhány kérdés segítségével megismerni a tanulási céljait és elvárásait, hogy a legmegfelelőbb tanulási tervet készíthessük el Önnek.',
  跳到: 'Ugrás ide',
  这座小山已经容不下你了: 'Ez a domb már nem tud befogadni',
  '您的正确率过高，推荐您跳级下一个词库': 'A pontossága túl magas, javasoljuk, hogy lépjen át a következő szókincs szintre',
  '自行跳过词库可能让您词汇掌握不扎实，且不能跳回原来的等级。为保证快速提升成绩，我们会从最基础的词库开始查漏补缺。当我们发现您已经掌握这个词库时，会主动提醒您更新到更高级的词汇库。':
    'A szókincs szintjeinek önálló átugrása instabil szókincs ismerethez vezethet, és nem térhet vissza az előző szintre. A gyors eredményjavulás érdekében a legalsó szintről kezdjük, hogy feltárjuk és pótoljuk a hiányosságokat. Ha úgy találjuk, hogy már elsajátította ezt a szintet, értesítjük, hogy lépjen fel egy magasabb szintre.',
  鹦鹉智学AI单词背诵: 'PapagájBot AI szókincs tanulás',
  '鹦鹉智学AI单词背诵会使用生词用AI生成文章来辅助背诵。这种背诵方式功能会让你的背诵记忆更加牢固、快速，也更加适应托福考试的要求。在我们过去做的实验中，100%的学生认为背诵效果提升，100%的学生认为这让单词背诵变得有趣。':
    'A PapagájBot AI szókincs tanulás AI által generált szövegeket használ a szavak memorizálásának segítésére. Ez a módszer stabilabb és gyorsabb memorizálást eredményez, jobban megfelelve a TOEFL követelményeinek. Korábbi kísérleteinkben a diákok 100%-a úgy találta, hogy ez a módszer javította a memorizálást, és érdekesebbé tette a szavak tanulását.',
  '鹦鹉智学 4步AI背诵法': 'PapagájBot AI 4 lépéses AI szókincs tanulási módszer',
  AI筛选生: 'AI szűrt új szavak',
  AI生词生成文章: 'AI által generált szöveg új szavakkal',
  语境单词背诵: 'Környezetben történő szókincs tanulás',
  AI模考复习: 'AI próbavizsga áttekintés',
  已学习单词: 'Már megtanult szavak',
  发现生词: 'Új szavak felfedezése',
  '的意思是？': 'jelentése?',
  不认识该词: 'Nem ismerem ezt a szót',
  恭喜你完成了今天的任务: 'Gratulálunk a mai feladat teljesítéséhez',
  返回单词首页: 'Vissza a szókincs főoldalra',
  直接进入背诵: 'Közvetlenül a memorizálásba lép',
  学习目标: 'Tanulási célok',
  问题1: '1. kérdés',
  '您目前的学习阶段是？': 'Mi a jelenlegi tanulási szakasza?',
  问题2: '2. kérdés',
  '您的学习目的是？': 'Mi a tanulási célja?',
  问题3: '3. kérdés',
  '您是否正在机构补习托福？': 'Jelenleg részt vesz TOEFL oktatáson intézményben?',
  问题: 'Kérdés',
  每日打卡: 'Napi bejelentkezés',
  每日学习30分钟以上即完成当日: 'Napi feladat teljesítése 30 percnél hosszabb tanulással',
  '打卡任务！加油哦！': 'Bejelentkezési feladat! Csak így tovább!',
  '暂无学习诊断，快去学习吧～': 'Nincs tanulási diagnózis, kezdjen tanulni~',
  '近7日平均分': 'Az elmúlt 7 nap átlagos pontszáma',
  错误率最高的题型: 'A legmagasabb hibaarányú feladattípus',
  您的当前词汇量为: 'Jelenlegi szókincse:',
  近七日访问次数: 'Az elmúlt 7 nap látogatásainak száma',
  选择你的托福考试时间: 'Válassza ki a TOEFL vizsga időpontját',
  年: 'Év',
  月: 'Hónap',
  忘记密码: 'Elfelejtett jelszó',
  综合模考: 'Átfogó próbavizsga',
  '做任务免费领取会员!': 'Teljesítsen feladatokat ingyenes tagság megszerzéséhez!',
  查看详情: 'Részletek megtekintése',
  '无限接近真实考试题，有几率在真实考试中复现。': 'Majdnem azonos a valós vizsgakérdésekkel, esély van rá, hogy a valós vizsgán is megjelenjenek.',
  免费版: 'Ingyenes verzió',
  '0元/月': '0 yuan/hónap',
  '免费使用我们所有模考，练习系统以及预测题，并获得个人问题诊断。':
    'Ingyenes hozzáférés az összes próbavizsgánkhoz, gyakorló rendszerünkhöz és előrejelzett kérdéseinkhez, valamint személyes problémadiagnózishoz.',
  '免费提供每日一次口语写作批改功能辅助您的学习。':
    'Ingyenes napi egyszeri beszéd- és írásjavítás a tanulás segítéséhez.',
  '5月前注册赠送1年留学顾问。扫描企业微信领取': 'Regisztráljon május előtt, hogy egyéves tanulmányi tanácsadót kapjon. Szkannelje be a Vállalati WeChat kódot a fogadáshoz.',
  最受欢迎: 'Legnépszerűbb',
  练习版会员: 'Gyakorló verzió tagság',
  '49元/月': '49 yuan/hónap',
  '您可使用我们软件的全部功能：包括每日30题批改，实时答疑，单词无痛背诵，全能版心理支持等功能。':
    'Hozzáférhet szoftverünk összes funkciójához: napi 30 kérdés javítása, valós idejű kérdések és válaszok, fájdalommentes szókincs tanulás, átfogó pszichológiai támogatás stb.',
  '赠送：三年留学顾问': 'Bónusz: Három éves tanulmányi tanácsadó',
  自适应学习版: 'Adaptív tanulási verzió',
  即将推出: 'Hamarosan érkezik',
  '在练习版会员的基础上，您将获得网课及每日智能任务功能。':
    'A gyakorló verzió tagságon felül kapni fog online kurzusokat és napi intelligens feladatokat.',
  '我们将附赠您12个月会员及终身留学顾问。': '12 hónapos tagság és életre szóló tanulmányi tanácsadó jár mellé.',
  扫码联系客服: 'Szkennelem a QR kódot a kapcsolatfelvételhez',
  领取礼包: 'Ajándékcsomag átvétele'
}